site_url : https://asalvadorc.github.io/BBDD
site_name: BD - Bases de Dades
theme: 
  name: readthedocs
  logo: assets/logocaminas.png
nav:
  - Tema 1-Introducció: https://asalvadorc.github.io/BBDD_Tema1
  - Tema 2-Model Entitat-Relació: https://asalvadorc.github.io/BBDD_Tema2

